# Generated by Django 4.0 on 2021-12-28 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('newsType', models.CharField(choices=[('企业要闻', '企业要闻'), ('行业新闻', '行业新闻'), ('通知公告', '通知公告')], max_length=50, verbose_name='新闻类型')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='展报')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=1, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'db_table': 'do_news',
                'ordering': ['-publish_date'],
            },
        ),
    ]
