# Generated by Django 4.0 on 2021-12-28 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-publish_date'], 'verbose_name': '通知公告', 'verbose_name_plural': '通知公告'},
        ),
    ]
