# Generated by Django 4.0 on 2021-12-29 05:57

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='内容'),
        ),
    ]
