# Generated by Django 4.0 on 2021-12-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='news_description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='news_photo',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='newsType',
            new_name='news_type',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='views',
            new_name='news_view',
        ),
    ]
