# Generated by Django 4.0 on 2021-12-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_description_news_news_description_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='dy_news',
        ),
    ]
