# Generated by Django 4.0 on 2021-12-30 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_code', models.CharField(max_length=30, verbose_name='机构编码')),
                ('institution_name', models.CharField(max_length=30, verbose_name='机构名称')),
                ('customer_name', models.CharField(max_length=20, verbose_name='客户姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别')),
                ('customer_type', models.CharField(choices=[('医生', '医生'), ('药剂师', '药剂师'), ('KDM', 'KDM')], default='医生', max_length=10, verbose_name='客户类型')),
                ('customer_duty', models.CharField(choices=[('主任医师', '主任医师'), ('副主任医师', '副主任医师'), ('主治医师', '主治医师'), ('住院医师', '住院医师'), ('医生', '医生'), ('实习医生', '实习医生'), ('其他', '其他')], default='其他', max_length=10, verbose_name='客户职务')),
                ('customer_title', models.CharField(choices=[('院长', '院长'), ('副院长', '副院长'), ('主任', '主任'), ('副主任', '副主任'), ('组长', '组长'), ('副组长', '副组长'), ('其他', '其他')], default='其他', max_length=10, verbose_name='客户职称')),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='客户电话')),
                ('approve_status', models.IntegerField(choices=[(1, '待审批'), (2, '审批通过'), (3, '审批拒绝')], default=1, verbose_name='审批状态')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
                'db_table': 'dy_customer',
                'ordering': ('-submit_date', '-approve_status'),
            },
        ),
    ]
