# Generated by Django 4.0 on 2021-12-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='图片描述')),
                ('photo', models.ImageField(blank=True, upload_to='award/', verbose_name='图片地址')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
                'db_table': 'do_contact',
            },
        ),
    ]
