# Generated by Django 4.0 on 2021-12-29 05:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='招聘岗位')),
                ('description', models.TextField(verbose_name='招聘要求')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '招聘信息',
                'verbose_name_plural': '招聘信息',
                'db_table': 'do_JD',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('ID_number', models.CharField(max_length=30, verbose_name='身份证号')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('birthday', models.DateField(default='2021-12-29', verbose_name='出生日期')),
                ('education_background', models.CharField(default='本科', max_length=50, verbose_name='学历')),
                ('graduate_institution', models.CharField(max_length=50, verbose_name='毕业院校')),
                ('major', models.CharField(max_length=50, verbose_name='主修专业')),
                ('apply_position', models.CharField(max_length=40, verbose_name='申请职位')),
                ('experience', models.TextField(blank=True, null=True, verbose_name='项目经验')),
                ('person_photo', models.ImageField(upload_to='contact/recruit/%Y-%m-%d', verbose_name='个人照片')),
                ('approve_status', models.IntegerField(choices=[(1, '待审批'), (2, '审批通过'), (3, '审批拒绝')], default=1, verbose_name='审批状态')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '简历信息',
                'verbose_name_plural': '简历信息',
                'db_table': 'do_resume',
                'ordering': ('-submit_date', '-approve_status'),
            },
        ),
    ]
