# Generated by Django 4.0 on 2021-12-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_jd_table_alter_resume_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contact',
            table='dy_contact',
        ),
    ]
