# Generated by Django 4.0 on 2021-12-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_contact_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birthday',
            field=models.DateField(default='2021-12-30', verbose_name='出生日期'),
        ),
    ]
