# Generated by Django 4.0 on 2022-01-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_alter_resume_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birthday',
            field=models.DateField(default='2022-01-14', verbose_name='出生日期'),
        ),
    ]
