# Generated by Django 4.0 on 2021-12-30 06:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction_code', models.CharField(max_length=30, verbose_name='辖区编码')),
                ('jurisdiction_name', models.CharField(max_length=30, verbose_name='辖区名称')),
                ('jurisdiction_level', models.CharField(blank=True, max_length=20, null=True, verbose_name='辖区级别')),
                ('remark', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('approve_status', models.IntegerField(choices=[(1, '待审批'), (2, '审批通过'), (3, '审批拒绝')], default=1, verbose_name='审批状态')),
                ('submit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='提交时间')),
            ],
            options={
                'verbose_name': '辖区信息',
                'verbose_name_plural': '辖区信息',
                'db_table': 'dy_jurisdiction',
                'ordering': ('-submit_date', '-approve_status'),
            },
        ),
    ]
