# Generated by Django 4.0 on 2021-12-29 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='资料名称')),
                ('file', models.FileField(blank=True, upload_to='Service/', verbose_name='文件资料')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '文件相关',
                'verbose_name_plural': '文件相关',
                'db_table': 'dy_document',
                'ordering': ['-publish_date'],
            },
        ),
    ]
