# Generated by Django 4.0 on 2021-12-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-publish_date'], 'verbose_name': '文件资料', 'verbose_name_plural': '文件资料'},
        ),
    ]
