# Generated by Django 4.0 on 2022-01-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('icon', models.ImageField(upload_to='icon/', verbose_name='头像')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('person_code', models.CharField(max_length=20, verbose_name='编号')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=5, verbose_name='性别')),
                ('ID_number', models.CharField(default='000000000000000000', max_length=18, verbose_name='身份证号')),
                ('birthday', models.DateTimeField(verbose_name='出生年月')),
                ('mobile_phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='联系电话')),
                ('wechat', models.CharField(blank=True, max_length=50, null=True, verbose_name='微信')),
                ('QQ', models.CharField(blank=True, max_length=50, null=True, verbose_name='QQ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('weibo', models.CharField(blank=True, max_length=50, null=True, verbose_name='微博')),
                ('hobby', models.CharField(blank=True, max_length=50, null=True, verbose_name='爱好')),
                ('graduate_institution', models.CharField(max_length=100, verbose_name='毕业院校')),
                ('education_background', models.CharField(choices=[('高中', '高中'), ('大专', '大专'), ('本科', '本科'), ('研究生-硕士', '研究生-硕士'), ('研究生-博士', '研究生-博士'), ('其他', '其他')], default='其他', max_length=30, verbose_name='学历')),
                ('major', models.CharField(max_length=100, verbose_name='主修专业')),
                ('score', models.FloatField(verbose_name='成绩')),
                ('residential_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='居住地址')),
                ('native_place', models.CharField(blank=True, max_length=100, null=True, verbose_name='籍贯')),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.BigIntegerField(blank=True, null=True, verbose_name='紧急联系方式')),
                ('state', models.IntegerField(choices=[(1, '有效'), (2, '失效')], default=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '人员管理',
                'verbose_name_plural': '人员管理',
                'db_table': 'dy_person',
            },
        ),
    ]
