# Generated by Django 4.0 on 2021-12-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='Award/')),
            ],
            options={
                'verbose_name': '荣誉资质',
                'verbose_name_plural': '荣誉资质',
                'db_table': 'Award',
            },
        ),
    ]
