# Generated by Django 4.0 on 2021-12-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.ImageField(blank=True, upload_to='award/'),
        ),
        migrations.AlterModelTable(
            name='award',
            table='do_award',
        ),
    ]
