# Generated by Django 4.0 on 2021-12-29 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_award_description_alter_award_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='award',
            table='dy_award',
        ),
    ]
