# Generated by Django 4.0 on 2022-01-10 08:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=30, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.UUIDField(default=uuid.UUID('eb0b8779-d9b9-4232-a22b-eafade68a569'), editable=False, primary_key=True, serialize=False),
        ),
    ]
