# Generated by Django 4.0 on 2021-12-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='alias',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='机构别名'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('专科医院', '专科医院'), ('综合医院', '综合医院'), ('单体药店', '单体药店'), ('连锁药店门店', '连锁药店门店'), ('连锁药店总店', '连锁药店总店'), ('诊所', '诊所'), ('其他', '其他')], default='其他', max_length=10, verbose_name='机构类别'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='机构电话'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='post_number',
            field=models.CharField(max_length=20, verbose_name='邮政编码'),
        ),
    ]
