# Generated by Django 4.0 on 2022-01-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='机构别名'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=50, verbose_name='机构名称'),
        ),
    ]
