# Generated by Django 4.0 on 2021-12-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_alter_institution_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='area',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='区县'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='机构电话'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='post_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='邮政编码'),
        ),
    ]
