# Generated by Django 4.0 on 2022-01-10 08:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_alter_institution_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(blank=True, max_length=30, verbose_name='编码'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.UUIDField(default=uuid.UUID('3a6e1418-6d3a-4805-8c65-faecfffd6f46'), editable=False, primary_key=True, serialize=False),
        ),
    ]
