# Generated by Django 4.0 on 2022-01-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_alter_institution_address_alter_institution_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_character',
            field=models.IntegerField(choices=[(1, 'Common'), (2, 'COE'), (3, 'Focus')], verbose_name='机构属性'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_property',
            field=models.IntegerField(choices=[(1, '民营医院'), (2, '公立医院'), (3, '专科医院'), (4, '未知')], verbose_name='机构性质'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_type',
            field=models.CharField(choices=[('专科医院', '专科医院'), ('综合医院', '综合医院'), ('单体药店', '单体药店'), ('连锁药店门店', '连锁药店门店'), ('连锁药店总店', '连锁药店总店'), ('诊所', '诊所'), ('其他', '其他')], default='其他', max_length=100, verbose_name='机构类别'),
        ),
    ]
