# Generated by Django 4.0 on 2022-01-10 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0004_alter_institution_institution_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.UUIDField(default=uuid.UUID('18a98735-52aa-409d-aec6-3cf56569f446'), editable=False, primary_key=True, serialize=False),
        ),
    ]
