# Generated by Django 4.0 on 2022-01-11 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0005_alter_institution_institution_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='institution_code',
            field=models.CharField(default='HA000001', max_length=20),
        ),
        migrations.AlterField(
            model_name='institution',
            name='institution_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
