# Generated by Django 4.0 on 2021-12-29 08:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='产品名称')),
                ('photo', models.ImageField(blank=True, upload_to='Product/', verbose_name='产品图片')),
                ('description', models.TextField(verbose_name='产品描述')),
                ('product_type', models.CharField(choices=[('家用机器人', '家用机器人'), ('智能门锁', '智能门锁'), ('人脸识别解决方案', '人脸识别解决方案')], max_length=100, verbose_name='产品类型')),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='产品价格')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('product_views', models.PositiveIntegerField(default=1, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '产品列表',
                'verbose_name_plural': '产品列表',
                'db_table': 'dy_product',
                'ordering': ['-publish_date'],
            },
        ),
    ]
